spring:
  application:
    name: SpringAI_Learn
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://rm-cn-fzh49j47s0001oho.rwlb.rds.aliyuncs.com:5432/postgres
    username: super_idea
    password: Dopa1997
  ai:
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:8127
        # stdio:
        # servers-configuration: classpath:mcp-servers.json


server:
  port: 8088
  servlet:
    context-path: /api

# springdoc-openapi配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.example.springai_learn.controller

# knife4j增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn


  mail:
    host: smtp.qq.com
    port: 465
    username: #替换为你的QQ账号
    # 注意：这里需要使用QQ邮箱的授权码，不是QQ密码
    # 获取方法：QQ邮箱 -> 设置 -> 账户 -> POP3/IMAP/SMTP/Exchange/CardDAV/CalDAV服务 -> 开启POP3/SMTP -> 生成授权码
    password: # 请替换为你的QQ邮箱授权码
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          connectiontimeout: 15000
          timeout: 15000
          writetimeout: 15000
          debug: true
    protocol: smtp
    test-connection: false  # 禁用启动时测试连接
    default-encoding: UTF-8

# searchApi
search-api:
  api-key: 你的API-KEY
